version: "3.5"

services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=knowledge_testing
    image: postgres:14-alpine3.18