"""Initial db structure

Revision ID: 04092ba7443f
Revises:

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04092ba7443f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('tests',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('success_percent', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('users',
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('fio', sa.VARCHAR(), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('answers',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=False),
    sa.Column('question_id', sa.BIGINT(), nullable=True),
    sa.Column('is_right', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('unique_question_answer', 'answers', ['text', 'question_id'], unique=True)
    op.create_table('attempts',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('test_id', sa.BIGINT(), nullable=True),
    sa.Column('answered_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('right_answers_percent', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('unique_user_test_attempt', 'attempts', ['username', 'test_id', 'answered_at'], unique=True)
    op.create_table('tests_questions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.BIGINT(), nullable=True),
    sa.Column('question_id', sa.BIGINT(), nullable=True),
    sa.Column('question_number', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('unique_test_question', 'tests_questions', ['test_id', 'question_id'], unique=True)
    op.create_index('unique_test_question_number', 'tests_questions', ['test_id', 'question_number'], unique=True)
    op.create_table('tokens',
    sa.Column('token', sa.UUID(as_uuid=False), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.username'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('results',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.BIGINT(), nullable=True),
    sa.Column('user_answer_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['user_answer_id'], ['answers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('unique_attempt_answer', 'results', ['attempt_id', 'user_answer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_attempt_question_answer', table_name='results')
    op.drop_table('results')
    op.drop_table('tokens')
    op.drop_index('unique_test_question_number', table_name='tests_questions')
    op.drop_index('unique_test_question', table_name='tests_questions')
    op.drop_table('tests_questions')
    op.drop_index('unique_user_test_attempt', table_name='attempts')
    op.drop_table('attempts')
    op.drop_index('unique_question_answer', table_name='answers')
    op.drop_table('answers')
    op.drop_table('users')
    op.drop_table('tests')
    op.drop_table('questions')
    # ### end Alembic commands ###
